# Generated by Django 3.1 on 2020-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
